### ISSUE TITLE
Possible bug in task "Using Action Sequences"

### ISSUE THREAD

**Issue by k0105** [apache/incubator-openwhisk-workshop#17]
When I select the task "Using Action Sequences" I get the following error:
```
/usr/local/lib/node_modules/openwhisk-workshop/exercises/using_action_sequences/exercise.js:35
    let found_message = false
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Workshopper.loadExercise (/usr/local/lib/node_modules/openwhisk-workshop/node_modules/workshopper/workshopper.js:484:14)
    at Workshopper.onselect (/usr/local/lib/node_modules/openwhisk-workshop/node_modules/workshopper/workshopper.js:501:23)
    at emitThree (events.js:97:13)
```

I'm on an updated Ubuntu 16.04 64bit Desktop with NodeJS 4.2.6 and OpenWhisk Workshop 0.1.0.

PS:
This also doesn't switch the task, so even when I look at the Markdown file instead I cannot verify my solution with `openwhisk-workshop verify`.

PPS:
I just noticed that the same problem occurs for me for all following tasks as well - the previous ones work, but the ones afterwards break. This is unfortunate - I solved the sequence task on my own, but I really liked the verification to know my solution meets the requirements.

**Comment by jthomas** [comment]
Hello, 

Can you try upgrading to Node.js version 6 or higher and try again? I need to state this dependency in the documentation.

**Comment by dgrove-oss** [comment]
Closing as project is being archived.
