### ISSUE TITLE
Add documentation on level of Node.js (4) and NPM required

### ISSUE THREAD

**Issue by krook** [apache/incubator-openwhisk-workshop#4]
I ran this on a Ubuntu 14.04 VM that I use as my `wsk` workstation. Installation worked, and I got the initial blue menu box, but when making a selection it died on the following error when choosing an exercise:

```
/usr/lib/node_modules/openwhisk-workshop/exercises/setting_up_cli/exercise.js:18
exec('wsk property get --apihost', {silent: true}, (code, stdout, stderr) => {
                                                                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Workshopper.loadExercise (/usr/lib/node_modules/openwhisk-workshop/node_modules/workshopper/workshopper.js:484:14)
    at Workshopper.onselect (/usr/lib/node_modules/openwhisk-workshop/node_modules/workshopper/workshopper.js:501:23)
    at EventEmitter.emit (events.js:107:17)
```

I was able to work around the problem by manually upgrading to Node 4, which wasn't evident on the first VM I tried, but it was when the packaged failed to install at all on another Ubuntu 14.04 box.

**Comment by jthomas** [comment]
Aha good spot @krook. 
I'll update the README to reflect this.
I've just tested this on Node v0.12 and although it does give you a warning on install, doesn't stop.

```
npm WARN engine openwhisk-workshop@0.0.2: wanted: {"node":">=4.0.0"} (current: {"node":"0.12.16","npm":"2.15.1"})
```

**Comment by jthomas** [comment]
I've just updated the README.
