### ISSUE TITLE
Missing start and end properties in hello-world-nodejs-delay response

### ISSUE THREAD

**Issue by jeancarl** [apache/incubator-openwhisk-workshop#6]
For the second exercise in Creating NodeJS Actions, response is missing the start and end properties. 

```
$openwhisk-workshop verify
✓ OpenWhisk Action hello-world-nodejs exists
✓ OpenWhisk Action hello-world-nodejs returns correct message
✓ OpenWhisk Action hello-world-nodejs-delay exists
/usr/local/lib/node_modules/openwhisk-workshop/exercises/creating_nodejs_actions/exercise.js:61
      const start_time = parseInt(stdout.match(/start": (\d+)/)[1], 10)
                                                               ^

TypeError: Cannot read property '1' of null
    at /usr/local/lib/node_modules/openwhisk-workshop/exercises/creating_nodejs_actions/exercise.js:61:64
    at /usr/local/lib/node_modules/openwhisk-workshop/node_modules/shelljs/src/exec.js:180:7
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Running it manually to get response:

```
wsk action invoke hello-world-nodejs-delay -b
ok: invoked hello-world-nodejs-delay with id -----------------
response:
{
    "result": {
        "message": "Hello World"
    },
    "status": "success",
    "success": true
}
```

**Comment by jthomas** [comment]
Hello. 

Are you using the Go or Python CLI?

**Comment by jeancarl** [comment]
Python

**Comment by jthomas** [comment]
Could you upgrade to the Go CLI? The Python client has been deprecated now. This should resolve your issue.
